2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Configure stats pid to 2568
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/.config/wandb/settings
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/Documents/wandb/settings
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:_log_setup():507] Logging user logs to /home/robot-lab/Documents/wandb/run-20230719_115105-bbpzbpuy/logs/debug.log
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:_log_setup():508] Logging internal logs to /home/robot-lab/Documents/wandb/run-20230719_115105-bbpzbpuy/logs/debug-internal.log
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:init():547] calling init triggers
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:init():596] starting backend
2023-07-19 11:51:05,377 INFO    MainThread:2568 [wandb_init.py:init():600] setting up manager
2023-07-19 11:51:07,387 ERROR   MainThread:2568 [wandb_init.py:init():1182] error
Traceback (most recent call last):
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-07-19 11:51:48,975 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Configure stats pid to 2568
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/.config/wandb/settings
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/Documents/wandb/settings
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:_log_setup():507] Logging user logs to /home/robot-lab/Documents/wandb/run-20230719_115148-d6qqf00n/logs/debug.log
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:_log_setup():508] Logging internal logs to /home/robot-lab/Documents/wandb/run-20230719_115148-d6qqf00n/logs/debug-internal.log
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:init():547] calling init triggers
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:init():596] starting backend
2023-07-19 11:51:48,976 INFO    MainThread:2568 [wandb_init.py:init():600] setting up manager
2023-07-19 11:51:50,982 ERROR   MainThread:2568 [wandb_init.py:init():1182] error
Traceback (most recent call last):
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
