2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Configure stats pid to 8959
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/.config/wandb/settings
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Loading settings from /home/robot-lab/Documents/wandb/settings
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:_log_setup():507] Logging user logs to /home/robot-lab/Documents/wandb/run-20230719_170713-a39livx4/logs/debug.log
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:_log_setup():508] Logging internal logs to /home/robot-lab/Documents/wandb/run-20230719_170713-a39livx4/logs/debug-internal.log
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:init():547] calling init triggers
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:init():596] starting backend
2023-07-19 17:07:13,500 INFO    MainThread:8959 [wandb_init.py:init():600] setting up manager
2023-07-19 17:07:13,501 INFO    MainThread:8959 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-07-19 17:07:13,502 INFO    MainThread:8959 [wandb_init.py:init():606] backend started and connected
2023-07-19 17:07:13,505 INFO    MainThread:8959 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-19 17:07:13,505 INFO    MainThread:8959 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-19 17:07:13,505 INFO    MainThread:8959 [wandb_init.py:init():705] updated telemetry
2023-07-19 17:07:13,507 INFO    MainThread:8959 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-19 17:07:13,638 ERROR   MainThread:8959 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-19 17:07:13,716 ERROR   MainThread:8959 [wandb_init.py:init():1172] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/home/robot-lab/anaconda3/envs/BVAE/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
